project:
  type: website
  output-dir: docs

website:
  title: "Visualización y Análisis de Datos Medioambientales"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Saryace/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: calendario.qmd
        text: Calendario
      - href: clases.qmd
        text: Clases
      - href: eval.qmd
        text: Evaluación-Final
format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

