---
title: "Calendario"
---

## 📆 Cronograma de Clases

+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| Semana   | Fecha    | Tema Principal                                         | Actividad Semanal                                                        | Observaciones                              |
+==========+==========+========================================================+==========================================================================+============================================+
| 1        | 15 ago   | Presentación del curso. Introducción a R y RStudio     | Instalación de R/Rstudio. Interés por tomar el curso.                    | No hay clase presencial                    |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        |                                                                          | Ver Videos en Canvas UC                    |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 2        | 22 ago   | Introducció a Git y GitHub                             | Crear cuenta de Github. Crear repositorio.                               | Clase online                               |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 3        | 29 ago   | Tidy data y proyectos en RStudio                       | Proponer orden de carpetas / readme / flujo de trabajo.                  | Clase presencial                           |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Identificar desafíos en los datos seleccionados                          |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 4        | 5 sept   | Lectura/escritura y exploración de datos               | Importar y explorar CSV y Excel.                                         | Clase presencial                           |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Definir dataset trabajo final.                                           |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 5        | 12 sept  | Introducción a `tidyverse`: `dplyr`, `readr`, `tibble` | Mostrar flujo de trabajo inicial (librerias, procesamiento datos crudos) | Clase presencial                           |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 6        | 19 sept  | **Feriado: Fiestas Patrias**                           | —                                                                        | *No hay clases ni actividades semanales*   |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 7        | 26 sept  | `ggplot2` I: básicos y `geom_*`                        | Crear primer gráfico (                                                   | Clase presencial                           |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 8        | 3 oct    | `ggplot2` II: personalización y facetas                | Crear segundo gráfico                                                    | —                                          |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 9        | 10 oct   | Manejo de fechas y unión de datos                      | Usar dataset de serie de tiempo.                                         | —                                          |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Desafío.                                                                 |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 10       | 17 oct   | Manejo de texto y limpieza                             | Usar dataset de texto.                                                   | —                                          |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Desafío.                                                                 |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 11       | 24 oct   | Modelos lineales y programación funcional              | Entrega de función personalizada                                         | —                                          |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Desafío                                                                  |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 12       | 31 oct   | **Feriado: Día Iglesias Evangélicas**                  | —                                                                        | *No hay clases presenciales*               |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 13       | 7 nov    | Estructuras de control: condicionales y bucles         | Loops y condicionales.                                                   | —                                          |
|          |          |                                                        |                                                                          |                                            |
|          |          |                                                        | Usando entrega semanal, desafío condicionales.                           |                                            |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 14       | 14 nov   | Introducción a datos geoespaciales en R                | Mapa con `sf` y `ggplot2`                                                | —                                          |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 15       | 21 nov   | Introducción a Python para usuarios de R               | Reescribir script de R en `pandas`                                       | —                                          |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+
| 16       | 28 nov   | Presentaciones finales y cierre del curso              | Presentación y entrega de informe final                                  | *Último día de clases según calendario UC* |
+----------+----------+--------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------+

## 📆 Asistencia a clases

La asistencia a clases **no es obligatoria**, pero es altamente recomendado asistir al menos al primer modulo de cada viernes. Durante el primer módulo se concentrará la mayor parte del contenido de la clase. En la segunda parte se responderán preguntas, se realizarán actividades complementarias o se dará tiempo seguro para avanzar en las actividades semanales. Este curso tiene **10 créditos**, por lo que para aprobar, se debe trabajar toda la semana complementariamente a los módulos de clase.
