---
title: "Course Materials"
---

## 📆 Calendario del Curso AGP3141 – Segundo Semestre 2025

| Semana | Tema                                                    | Slides                                                                                    | Datos                                                                      | Referencias                                                                        |     |
|--------|---------------------------------------------------------|-------------------------------------------------------------------------------------------|----------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----|
| 1      | Presentación del curso. Introducción a R y RStudio      | 📄 No slides                                                                              | —                                                                          | Videos en Canvas                                                                   |     |
| 2      | Introducción a Git, GitHub e investigación reproducible | 📄 [reproducibilidad](https://saryace.github.io/environ-dataviz-uc/slides/01-semana.html) | —                                                                          | [Happy Git with R](https://happygitwithr.com/) + otras (ver slides)                |     |
| 3      | Tidy data y proyectos en RStudio                        | 📄 [reproducibilidad](https://saryace.github.io/environ-dataviz-uc/slides/03-semana.html) | [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/)          | [R4DS](https://es.r4ds.hadley.nz/)                                                 |     |
| 4      | Lectura/escritura y exploración de datos                | 📄 formatos                                                                               | [Agrometeorologia](https://agrometeorologia.cl/)                           | [R4DS](https://es.r4ds.hadley.nz/)                                                 |     |
| 5      | Introducción a `tidyverse`: `dplyr`, `readr`, `tibble`  | 📄 tidyverse-basico                                                                       | [EDI Data Portal](https://portal.edirepository.org/nis/advancedSearch.jsp) | [R4DS](https://es.r4ds.hadley.nz/)                                                 |     |
| 6      | **Feriado: Fiestas Patrias**                            | —                                                                                         | —                                                                          | —                                                                                  |     |
| 7      | `ggplot2` I: básicos y `geom_*`                         | 📄 ggplot2-A                                                                              | —                                                                          | [Modern Data Visualization with R](https://rkabacoff.github.io/datavis/index.html) |     |
| 8      | `ggplot2` II: personalización y facetas                 | 📄 ggplot2-B                                                                              | —                                                                          | [Modern Data Visualization with R](https://rkabacoff.github.io/datavis/index.html) |     |
| 9      | Manejo de fechas y unión de datos                       | 📄 fechas-join                                                                            | —                                                                          | [R4DS](https://es.r4ds.hadley.nz/)                                                 |     |
| 10     | Manejo de texto y limpieza                              | 📄 texto                                                                                  | —                                                                          | —                                                                                  |     |
| 11     | Modelos lineales y programación funcional               | 📄 purrr-reg                                                                              | —                                                                          | —                                                                                  |     |
| 12     | **Feriado: Día Iglesias Evangélicas**                   | —                                                                                         | —                                                                          | —                                                                                  |     |
| 13     | Condicionales y bucles                                  | 📄 loop                                                                                   | —                                                                          | —                                                                                  |     |
| 14     | Introducción a datos geoespaciales en R                 | 📄 geoespacial-R                                                                          | —                                                                          | —                                                                                  |     |
| 15     | Introducción a Python para usuarios de R                | 📄 r-python                                                                               | —                                                                          | —                                                                                  |     |
| 16     | Presentaciones finales y cierre del curso               | —                                                                                         | Dataset final                                                              | —                                                                                  | —   |
